[2025-10-22T10:22:43.704+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-22T10:22:43.782+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_db.staging_table manual__2025-10-22T10:22:40.685840+00:00 [queued]>
[2025-10-22T10:22:43.812+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_db.staging_table manual__2025-10-22T10:22:40.685840+00:00 [queued]>
[2025-10-22T10:22:43.815+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-22T10:22:43.866+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): staging_table> on 2025-10-22 10:22:40.685840+00:00
[2025-10-22T10:22:43.879+0000] {standard_task_runner.py:63} INFO - Started process 4967 to run task
[2025-10-22T10:22:43.888+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'update_db', 'staging_table', 'manual__2025-10-22T10:22:40.685840+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpkqrsc_sb']
[2025-10-22T10:22:43.895+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask staging_table
[2025-10-22T10:22:44.146+0000] {task_command.py:426} INFO - Running <TaskInstance: update_db.staging_table manual__2025-10-22T10:22:40.685840+00:00 [running]> on host ddff07f854c7
[2025-10-22T10:22:44.407+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='gidiboateng200@gmail.com' AIRFLOW_CTX_DAG_OWNER='dataengineers' AIRFLOW_CTX_DAG_ID='update_db' AIRFLOW_CTX_TASK_ID='staging_table' AIRFLOW_CTX_EXECUTION_DATE='2025-10-22T10:22:40.685840+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-22T10:22:40.685840+00:00'
[2025-10-22T10:22:44.438+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-22T10:22:44.468+0000] {base.py:84} INFO - Using connection ID 'postgres_db_yt_elt' for task execution.
[2025-10-22T10:22:44.496+0000] {data_loading.py:12} INFO - Processing file: YT_data_2025-10-22
[2025-10-22T10:22:44.563+0000] {base.py:84} INFO - Using connection ID 'postgres_db_yt_elt' for task execution.
[2025-10-22T10:22:44.584+0000] {base.py:84} INFO - Using connection ID 'postgres_db_yt_elt' for task execution.
[2025-10-22T10:22:44.600+0000] {data_modification.py:40} ERROR - Error inserting row with Video_ID: yWEUL3crU_E
[2025-10-22T10:22:44.606+0000] {dataware_house.py:44} ERROR - An error occurred during the update of staging table: 'publishedAt'
[2025-10-22T10:22:44.611+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-22T10:22:44.616+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/datawarehouse/dataware_house.py", line 45, in staging_table
    raise e
  File "/opt/airflow/dags/datawarehouse/dataware_house.py", line 28, in staging_table
    insert_row(cur, conn, schema, row)
  File "/opt/airflow/dags/datawarehouse/data_modification.py", line 41, in insert_row
    raise e
  File "/opt/airflow/dags/datawarehouse/data_modification.py", line 15, in insert_row
    cur.execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/extras.py", line 236, in execute
    return super().execute(query, vars)
KeyError: 'publishedAt'
[2025-10-22T10:22:44.663+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=update_db, task_id=staging_table, run_id=manual__2025-10-22T10:22:40.685840+00:00, execution_date=20251022T102240, start_date=20251022T102243, end_date=20251022T102244
[2025-10-22T10:22:44.714+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 32 for task staging_table ('publishedAt'; 4967)
[2025-10-22T10:22:44.788+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-22T10:22:44.828+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
