[2025-10-22T10:18:00.728+0000] {scheduler_job_runner.py:843} ERROR - Executor reports task instance <TaskInstance: update_db.staging_table manual__2025-10-22T10:17:57.081172+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
